---
- name: Install epel-release
  yum: name={{ item }} state=latest
  with_items:
      - epel-release
      - yum-utils
      # - python-pip
      - git

# - name: Pip install setuptools
#   pip:
#     name: setuptools
#     state: latest
    # executable: pip3.6
    
# - name: Pip install docker
#   pip:
#     name: docker
#     state: latest
    # executable: pip3.6

# - name: pip update
#   shell: pip install --upgrade pip
#   become: yes

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0
  become: yes

- name: Enable Docker Test repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-test'
    option: enabled
    value: 0
  become: yes

- name: Install Docker
  yum:
    name: docker-ce
    state: latest
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Shell 
  shell: curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  become: yes

- name: grant permissions
  shell: chmod +x /usr/local/bin/docker-compose
  become: yes

- name: usermod -aG docker mp
  shell: usermod -aG docker mp
  become: yes

- name: Install docker-compose
  yum: name={{ item }} state=latest
  with_items:
      - docker-compose
