---

- name: Install docker-compose and fitches
  hosts: monitor01
  become: yes

  tasks:
  # tasks file for pgbouncer
  - name: Install epel-release
    yum: name={{ item }} state=latest
    with_items:
        - epel-release

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - name: Enable Docker Edge repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-edge'
      option: enabled
      value: 0

  - name: Enable Docker Test repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-test'
      option: enabled
      value: 0
 
  - name: Install device-mapper-persistent-data
    yum: name={{ item }} state=latest
    with_items:
        - python-pip
        - docker-compose
        - docker
        - yum-utils

  - name: Install docker-py
    pip: 
      name: docker-py
    executable: pip3.6
    virtualenv_command: /usr/bin/python3