---

# - name: open ports 3000, 9090, 9100
#   shell: firewall-cmd --permanent --add-port={{item}}/tcp
#   with_items:
#    - 3000
#    - 9090
#    - 9100

# - name: reload firewall
#   shell: firewall-cmd --reload

# - name: Make DIRs PostgreSQL
#   file:
#     path: /root/
#     owner: root
#     group: root
#     state: directory
#   become: yes

# - name: ssh-keyscan
#   shell: ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
#   become_user: root

# - name: git user.email
#   shell: git config --global user.email "a.katruk@cometrica.ru"
           
# - name: git user.name
#   shell: git config --global user.name "Andrey Katruk"

- name: Clone a private repository into /root 
  git:
   repo: git@gitlab.com:cometrica/prosvet/devops.git
   dest: /root/git/
   accept_hostkey: yes
  become_user: root

- name: put custom config
  template: src=git_commit.sh dest=/root/git/git_commit.sh backup=yes

- name: x permission
  shell: chmod +x /root/git/git_commit.sh
  become: yes

- name: Creates a cron file under /srv/ autocommit for gitlab monitoring
  cron:
    name: autocommit gitlab monitoring
    weekday: "*"
    minute: "0"
    hour: "2"
    user: root
    job: "/root/git/prometheus/git_commit.sh"

- debug:
   msg: AUTOMATIVALY DOESNT WORK docker-compose -f /root/git/docker-compose.yml up -d

- name: run Docker-compose ansible
  shell: docker-compose -f /root/git/prometheus/docker-compose.yml up -d
  become: yes
  become_user: root
  ignore_errors: yes
