---

- name: open ports 3000, 9090, 9100
  shell: firewall-cmd --permanent --add-port={{item}}/tcp
  with_items:
   - 3000
   - 9090
   - 9100

- name: reload firewall
  shell: firewall-cmd --reload

- name: Make DIRs PostgreSQL
  file:
    path: /home/mp/git/
    owner: mp
    group: mp
    state: directory
  become: yes

- name: ssh-keyscan
  shell: ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
  become_user: mp

- name: git user.email
  shell: git config --global user.email "a.katruk@cometrica.ru"
           
- name: git user.name
  shell: git config --global user.name "Andrey Katruk"

- name: Clone a private repository into /home/mp 
  git:
   repo: git@gitlab.com:cometrica/prosvet/devops.git
   dest: /home/mp/git/
   accept_hostkey: yes
  become_user: mp

- name: put custom config
  template: src=git_commit.sh dest=/home/mp/git/prometheus/git_commit.sh backup=yes

- name: x permission
  shell: chmod +x /home/mp/git/prometheus/git_commit.sh
  become: yes

- name: Creates a cron file under /srv/ autocommit for gitlab monitoring
  cron:
    name: autocommit gitlab monitoring
    weekday: "*"
    minute: "0"
    hour: "2"
    user: root
    job: "/home/mp/git/prometheus/git_commit.sh"

- name: run Docker-compose ansible
  shell: docker-compose -f /home/mp/git/prometheus/docker-compose.yml up -d
  become: yes
  become_user: root
