---

# - name: Install epel-release
#   yum: 
#     name: epel-release 

# - name: Install  python
#   yum: 
#     name: python-pip 

# - name: open firewall 27017
#   shell: firewall-cmd --permanent --add-port={{item}}/tcp
#   with_items:
#    - 27017

# - name: reload firewall
#   shell: firewall-cmd --reload

# - name: install pymongo
#   yum: 
#     name: pymongo

# - name: Configure the package management system
#   template: 
#     src: mongodb-org-4.2.repo.j2 
#     dest: /etc/yum.repos.d/mongodb-org-4.2.repo 
#     backup: yes

# - name: install mongodb
#   yum: 
#     name: mongodb-org 
#     state: latest

# - name: Configure the package management system with replica
#   template: 
#     src: mongod.conf.j2 
#     dest: /etc/mongod.conf 
#     backup: yes

# - name: start service mongod
#   service: 
#    name: mongod.service
#    state: started
  
- name: copy initRS script
  template:
    src: roles/mongodb/templates/initRS.j2
    dest: /tmp/initRS.js
    owner: mongod
    group: mongod

- name: initiate replica set from first primary
  shell: mongo < /tmp/initRS.js

- name: Copy keyfile for replica
  template:
    srv: roles/mongodb/templates/keyFile.j2
    dest: /var/lib/mongo/keyFile
    mode: 600
    owner: mongod
    group: mongod

- name: grant permission for keyFile
  shell: chcon system_u:object_r:mongod_var_lib_t:s0 /var/lib/mongo/keyFile

- name: Restart service mongodb
  service:
    name: mongod
    state: restarted