---

- name: Install  python
  yum: name=epel-release state=latest

- name: Install  python
  yum: name=python-pip state=latest

- name: install python packages
  pip: name=pymongo

- name: Configure the package management system
  template: src=mongodb-org-4.2.repo.j2 dest=/etc/yum.repos.d/mongodb-org-4.2.repo backup=yes

- name: install mongodb
  yum: name=mongodb-org state=latest

- name: Disable SELinux
  selinux:
    state: disabled

- name: Configure the package management system with replica
  template: src=mongod.conf1.j2 dest=/etc/mongod.conf backup=yes

- name: start service mongod
  service: 
   name: mongod.service
   state: started

- name: add usr
  mongodb_user:
    database: admin
    name: useradmin
    roles: userAdminAnyDatabase
    password: 12345DB
    state: present
  
- name: Configure key
  template:
    src: keyfile.j2 
    dest: /var/lib/mongo/keyfile 
    backup: yes
    owner: mongod
    group: mongod
    mode: 0600

- name: Configure the package management system with replica
  template: src=mongod.conf2.j2 dest=/etc/mongod.conf backup=yes force=yes  

- name: restart service mongod
  service: 
   name: mongod.service
   state: restarted

- name: open firewall 27017
  shell: firewall-cmd --permanent --add-port={{item}}/tcp
  with_items:
   - 27017

- name: reload firewall
  shell: firewall-cmd --reload
